#ifndef SO2_GAME_B_INTERNAL_ENUMS_H
#define SO2_GAME_B_INTERNAL_ENUMS_H

typedef enum
{
    ENTITY_HUMAN = 1, ENTITY_BOT, ENTITY_BEAST, ENTITY_TO_DESTROY

} EntityType;

typedef enum
{
    K_NONE, K_LEFT, K_RIGHT, K_UP, K_DOWN, K_QUIT

} KeyCode;

typedef enum
{
    ACTION_NONE, ACTION_ACCEPTED, ACTION_REJECTED
} ActionsStatus;

typedef enum
{
    JOIN_UNKNOWN, JOIN_ACCEPTED, JOIN_REJECTED
} JoinStatus;

#endif //SO2_GAME_B_INTERNAL_ENUMS_H
