#ifndef SO2_GAME_B_INTERNAL_DEFINES_H
#define SO2_GAME_B_INTERNAL_DEFINES_H

#define MAX_PLAYERS 4
#define MAX_BEASTS 2
#define MAX_ENTITIES MAX_PLAYERS + MAX_BEASTS

#define DEFAULT_MAP_PATH "../default_map.txt"

#define SHM_JOIN_REQUEST "SO2_GAME_JOIN_REQUEST"
#define SHM_PLAYER1 "SO2_GAME_PLAYER1"
#define SHM_PLAYER2 "SO2_GAME_PLAYER2"
#define SHM_PLAYER3 "SO2_GAME_PLAYER3"
#define SHM_PLAYER4 "SO2_GAME_PLAYER4"
#define SHM_BEAST1 "SO2_GAME_BEAST1"
#define SHM_BEAST2 "SO2_GAME_BEAST2"

#define SERVER_LEGAL_KEYS(n) ((n) == 'c' || (n) == 't' || (n) == 'T')

#define PLAYER_FOV_X 5
#define PLAYER_FOV_Y 5


#endif //SO2_GAME_B_INTERNAL_DEFINES_H
